### ISSUE TITLE
Для каких целей используется фреймворк Kohana в CodeX Media?

### ISSUE THREAD

**Issue by amiller911** [codex-team/codex.media#460]

**Comment by gohabereg** [comment]
Hi there!

Kohana — HMVC framework that is used as base project skeleton.
We chose it because of simplicity, robustness and speed. Also we have extensive experience with it and love it much!
Unfortunately, Kohana project was closed at 2017 and the latest version doesn't support PHP7. However, there are some going on forks compatible with PHP7 and supported by community, so we will move to some of them in the future.
